import type { EvergreenArticleType } from '@/lib/ai/evergreen-schemas';

export interface EvergreenTopic {
  topic: string;
  primaryKeyword: string;
  articleType: EvergreenArticleType;
  difficulty: number;
  secondaryKeywords: string[];
}

export interface EvergreenCluster {
  name: string;
  slug: string;
  pillarKeyword: string;
  dbCategory: string;
  description: string;
  topics: EvergreenTopic[];
}

const t = (
  topic: string,
  kw: string,
  type: EvergreenArticleType,
  diff: number,
  sec: string[],
): EvergreenTopic => ({ topic, primaryKeyword: kw, articleType: type, difficulty: diff, secondaryKeywords: sec });

export const CLUSTERS: EvergreenCluster[] = [
  // ── 1. Τεχνητή Νοημοσύνη ────────────────────────────────────────────────────
  {
    name: 'Τεχνητή Νοημοσύνη',
    slug: 'ai-core',
    pillarKeyword: 'τεχνητή νοημοσύνη',
    dbCategory: 'AI',
    description: 'Πλήρης οδηγός για την Τεχνητή Νοημοσύνη — από τα βασικά έως τις προχωρημένες εφαρμογές. Μάθετε πώς λειτουργεί η AI, ποιες είναι οι τύποι της, πού χρησιμοποιείται σήμερα και ποιες είναι οι ηθικές και κοινωνικές προκλήσεις που φέρνει μαζί της.',
    topics: [
      t('Τι είναι η Τεχνητή Νοημοσύνη', 'τεχνητή νοημοσύνη', 'what-is', 25, ['AI', 'machine learning', 'αλγόριθμοι']),
      t('Ιστορία της Τεχνητής Νοημοσύνης', 'ιστορία τεχνητής νοημοσύνης', 'analysis', 40, ['Alan Turing', 'AI ιστορία', 'milestones']),
      t('Τύποι Τεχνητής Νοημοσύνης: Narrow vs General vs Super AI', 'τύποι AI', 'explainer', 35, ['AGI', 'narrow AI', 'superintelligence']),
      t('AI vs Ανθρώπινη Νοημοσύνη: Πλεονεκτήματα και Όρια', 'AI vs ανθρώπινη νοημοσύνη', 'comparison', 40, ['human brain', 'cognitive computing', 'AI limits']),
      t('Πώς Μαθαίνει η Τεχνητή Νοημοσύνη', 'πώς μαθαίνει AI', 'explainer', 40, ['training data', 'neural networks', 'AI learning']),
      t('AI στην Καθημερινή Ζωή: 20 Χρήσεις που Αγνοείς', 'AI καθημερινή ζωή', 'analysis', 25, ['AI εφαρμογές', 'AI smartphone', 'recommendation systems']),
      t('AI στην Ιατρική: Διάγνωση, Θεραπεία και Έρευνα', 'AI ιατρική', 'analysis', 45, ['medical AI', 'ιατρική διάγνωση', 'healthcare AI']),
      t('AI στην Εκπαίδευση: Εξατομικευμένη Μάθηση', 'AI εκπαίδευση', 'analysis', 40, ['personalized learning', 'AI tutors', 'edtech']),
      t('AI στις Επιχειρήσεις: Πώς Αυξάνει την Αποδοτικότητα', 'AI επιχειρήσεις', 'guide', 35, ['business AI', 'AI automation', 'ROI AI']),
      t('Ηθική Τεχνητής Νοημοσύνης: Τα Μεγάλα Ερωτήματα', 'ηθική AI', 'analysis', 50, ['AI ethics', 'bias', 'fairness AI']),
      t('AI Bias: Τι Είναι και Πώς να το Αποφύγεις', 'AI bias', 'explainer', 50, ['algorithmic bias', 'fairness', 'training data bias']),
      t('AI Safety: Γιατί Είναι Κρίσιμη', 'AI safety', 'analysis', 55, ['AI alignment', 'superintelligence risks', 'Anthropic OpenAI']),
      t('AI Regulation: Πώς Ρυθμίζεται η Τεχνητή Νοημοσύνη', 'ρύθμιση AI', 'analysis', 55, ['EU AI Act', 'AI governance', 'AI laws']),
      t('AI και Ιδιωτικότητα: Ποια Δεδομένα Συλλέγει', 'AI απόρρητο', 'analysis', 45, ['privacy AI', 'data collection', 'GDPR AI']),
      t('Ποια Επαγγέλματα Απειλεί η AI', 'AI και εργασία', 'analysis', 35, ['αυτοματοποίηση επαγγελμάτων', 'AI job displacement', 'future jobs']),
      t('Πώς να Ξεκινήσεις να Μαθαίνεις AI από Μηδέν', 'εκμάθηση AI', 'guide', 25, ['AI courses', 'machine learning basics', 'AI resources']),
      t('AI Agents: Τι Είναι και Πώς Λειτουργούν', 'AI agents', 'what-is', 45, ['autonomous agents', 'agentic AI', 'AI workflows']),
      t('Multimodal AI: Εικόνες, Κείμενο και Ήχος Μαζί', 'multimodal AI', 'explainer', 50, ['GPT-4V', 'Gemini', 'multimodal models']),
      t('AI-Generated Content: Οφέλη, Κίνδυνοι και Ανίχνευση', 'AI generated content', 'analysis', 35, ['AI content detection', 'deepfakes', 'synthetic media']),
      t('Computer Vision: Πώς Βλέπει ο Υπολογιστής', 'computer vision', 'what-is', 55, ['image recognition', 'object detection', 'convolutional networks']),
      t('AI για Μικρές Επιχειρήσεις: Πρακτικός Οδηγός', 'AI μικρές επιχειρήσεις', 'guide', 25, ['AI tools SMB', 'automation small business', 'affordable AI']),
      t('Τα Καλύτερα AI Tools του 2024', 'καλύτερα AI tools', 'best-of', 20, ['ChatGPT', 'Claude', 'Gemini', 'AI productivity']),
      t('Recommendation Systems: Πώς Σου Προτείνει το Netflix', 'recommendation systems', 'explainer', 50, ['collaborative filtering', 'Netflix algorithm', 'personalization']),
      t('Τι είναι το Synthetic Data στην AI', 'synthetic data AI', 'explainer', 60, ['data augmentation', 'training data', 'privacy preserving']),
      t('Μελλοντικές Τάσεις Τεχνητής Νοημοσύνης', 'μέλλον AI τεχνητή νοημοσύνη', 'analysis', 40, ['AI trends', 'AGI', 'future of AI']),
    ],
  },

  // ── 2. Machine Learning & Data Science ─────────────────────────────────────
  {
    name: 'Machine Learning',
    slug: 'machine-learning',
    pillarKeyword: 'machine learning',
    dbCategory: 'AI',
    description: 'Εξερευνήστε τον κόσμο του Machine Learning και της Data Science. Από supervised learning και neural networks έως MLOps και AutoML — αναλυτικοί οδηγοί για αρχάριους και επαγγελματίες που θέλουν να κατανοήσουν πώς τα μηχανήματα μαθαίνουν από δεδομένα.',
    topics: [
      t('Τι είναι το Machine Learning', 'machine learning', 'what-is', 35, ['supervised learning', 'εκμάθηση μηχανής', 'AI']),
      t('Supervised vs Unsupervised vs Reinforcement Learning', 'τύποι machine learning', 'explainer', 50, ['supervised', 'unsupervised', 'reinforcement learning']),
      t('Τι είναι τα Neural Networks', 'νευρωνικά δίκτυα', 'explainer', 55, ['deep learning', 'layers', 'backpropagation']),
      t('Τι είναι το Deep Learning', 'deep learning', 'explainer', 50, ['neural networks', 'CNN', 'RNN']),
      t('Τι είναι το Natural Language Processing (NLP)', 'NLP natural language processing', 'what-is', 45, ['text analysis', 'sentiment analysis', 'NLP']),
      t('Τι είναι το Transfer Learning', 'transfer learning', 'explainer', 60, ['pre-trained models', 'fine-tuning', 'BERT']),
      t('Τι είναι το Reinforcement Learning', 'reinforcement learning', 'explainer', 65, ['reward function', 'agent environment', 'Q-learning']),
      t('Τι είναι τα Embeddings στην AI', 'embeddings AI', 'explainer', 65, ['word2vec', 'vector space', 'semantic similarity']),
      t('Τι είναι το RAG (Retrieval-Augmented Generation)', 'RAG retrieval augmented generation', 'explainer', 65, ['LLM', 'knowledge base', 'vector database']),
      t('Τι είναι η Data Science', 'data science', 'what-is', 30, ['data analysis', 'Python', 'statistics']),
      t('Τι είναι το Feature Engineering', 'feature engineering machine learning', 'explainer', 65, ['feature selection', 'data preparation', 'ML pipeline']),
      t('Τι είναι το Overfitting και Underfitting', 'overfitting underfitting machine learning', 'explainer', 55, ['model generalization', 'bias variance tradeoff', 'regularization']),
      t('Τι είναι το Big Data Analytics', 'big data analytics', 'what-is', 40, ['Hadoop', 'Spark', 'data lakes']),
      t('Τι είναι το Data Preprocessing', 'data preprocessing machine learning', 'guide', 50, ['data cleaning', 'normalization', 'missing values']),
      t('Τι είναι τα Decision Trees', 'decision trees algorithm', 'explainer', 45, ['classification', 'random forest', 'CART']),
      t('Τι είναι το Random Forest', 'random forest algorithm', 'explainer', 50, ['ensemble learning', 'bagging', 'decision trees']),
      t('Τι είναι τα Recommendation Systems', 'recommendation systems machine learning', 'explainer', 50, ['collaborative filtering', 'content-based', 'hybrid systems']),
      t('Τι είναι το MLOps', 'MLOps machine learning operations', 'what-is', 60, ['model deployment', 'CI/CD ML', 'model monitoring']),
      t('Εργαλεία Data Science: Python, R, SQL', 'εργαλεία data science', 'best-of', 30, ['Python data science', 'Pandas', 'scikit-learn']),
      t('Τι είναι το Federated Learning', 'federated learning', 'explainer', 70, ['privacy ML', 'distributed learning', 'edge AI']),
      t('Τι είναι το AutoML', 'AutoML automated machine learning', 'what-is', 50, ['automated ML', 'H2O', 'Google AutoML']),
      t('Πώς να Αξιολογείς Ένα ML Model', 'αξιολόγηση machine learning model', 'guide', 55, ['accuracy', 'precision recall', 'F1 score']),
      t('Τι είναι ο Αλγόριθμος k-Means Clustering', 'k-means clustering', 'explainer', 60, ['unsupervised learning', 'clustering algorithms', 'data segmentation']),
      t('Τι είναι το Time Series Forecasting', 'time series forecasting', 'explainer', 55, ['ARIMA', 'LSTM', 'temporal data']),
      t('Μέλλον του Machine Learning', 'μέλλον machine learning', 'analysis', 40, ['AI trends', 'quantum ML', 'neuromorphic computing']),
    ],
  },

  // ── 3. Generative AI & LLMs ─────────────────────────────────────────────────
  {
    name: 'Generative AI',
    slug: 'generative-ai',
    pillarKeyword: 'generative AI',
    dbCategory: 'AI',
    description: 'Ο ολοκληρωμένος οδηγός για το Generative AI και τα Large Language Models. Από το ChatGPT και το Claude έως το prompt engineering και τη δημιουργία εικόνων, βίντεο και μουσικής με AI — ανακαλύψτε πώς η Γεννητική Τεχνητή Νοημοσύνη αλλάζει τον τρόπο που δημιουργούμε περιεχόμενο.',
    topics: [
      t('Τι είναι τα Large Language Models (LLMs)', 'large language models LLM', 'what-is', 40, ['GPT', 'transformer', 'language model']),
      t('Πώς Λειτουργεί το ChatGPT', 'ChatGPT πώς λειτουργεί', 'explainer', 30, ['GPT-4', 'OpenAI', 'conversational AI']),
      t('Τι είναι το Prompt Engineering', 'prompt engineering', 'guide', 35, ['ChatGPT prompts', 'AI prompting', 'better AI results']),
      t('Τι είναι τα Generative AI Models', 'generative AI models', 'what-is', 30, ['DALL-E', 'Midjourney', 'Stable Diffusion']),
      t('Πώς Δημιουργεί Εικόνες η AI', 'AI δημιουργία εικόνων', 'explainer', 35, ['diffusion models', 'image generation', 'text-to-image']),
      t('Τι είναι το Fine-tuning LLM', 'fine-tuning LLM', 'explainer', 60, ['model customization', 'LoRA', 'RLHF']),
      t('Τι είναι το Context Window στα LLMs', 'context window LLM', 'explainer', 50, ['token limit', 'long context', 'memory LLM']),
      t('Σύγκριση AI Chatbots: ChatGPT vs Claude vs Gemini', 'σύγκριση ChatGPT Claude Gemini', 'comparison', 25, ['AI comparison', 'best chatbot', 'GPT vs Claude']),
      t('Πώς να Χρησιμοποιείς το ChatGPT για Εργασία', 'ChatGPT για εργασία', 'guide', 20, ['ChatGPT productivity', 'AI workflow', 'ChatGPT tips']),
      t('Τι είναι τα AI Hallucinations', 'AI hallucinations', 'explainer', 35, ['LLM errors', 'factual accuracy', 'AI mistakes']),
      t('Τι είναι το Chain-of-Thought Prompting', 'chain of thought prompting', 'explainer', 55, ['COT', 'reasoning LLM', 'advanced prompting']),
      t('AI για Content Creation: Πλεονεκτήματα και Παγίδες', 'AI δημιουργία περιεχομένου', 'guide', 25, ['AI writing', 'AI content tools', 'SEO AI content']),
      t('Τα Καλύτερα AI Coding Tools', 'AI coding assistant', 'best-of', 30, ['GitHub Copilot', 'Cursor', 'AI programming']),
      t('Τι είναι το Tokenization στα LLMs', 'tokenization LLM', 'explainer', 60, ['tokens', 'BPE', 'vocabulary']),
      t('Τι είναι η Temperature στα AI Models', 'temperature AI', 'explainer', 50, ['AI randomness', 'sampling', 'top-p']),
      t('AI Music Generation: Πώς Δημιουργεί Μουσική η AI', 'AI μουσική δημιουργία', 'what-is', 35, ['Suno', 'Udio', 'AI composers']),
      t('AI Video Generation: Text-to-Video Τεχνολογία', 'AI video generation', 'what-is', 35, ['Sora', 'Runway', 'AI video']),
      t('AI Voice Cloning: Ηθική και Τεχνολογία', 'AI voice cloning', 'what-is', 40, ['voice AI', 'deepfake voice', 'ElevenLabs']),
      t('Τι είναι το Multimodal AI', 'multimodal AI models', 'what-is', 45, ['GPT-4V', 'image text audio AI', 'vision LLM']),
      t('Πώς λειτουργεί η Diffusion AI', 'diffusion models AI', 'explainer', 60, ['DDPM', 'stable diffusion', 'score matching']),
      t('Τι είναι το RLHF (Reinforcement Learning from Human Feedback)', 'RLHF', 'explainer', 65, ['ChatGPT training', 'human feedback AI', 'alignment']),
      t('Πρακτικοί Τρόποι να Βελτιώσεις τα AI Prompts σου', 'βελτίωση AI prompts', 'tutorial', 25, ['prompt tips', 'few-shot prompting', 'system prompt']),
      t('Τι είναι το RAG vs Fine-tuning', 'RAG vs fine-tuning', 'comparison', 60, ['LLM customization', 'knowledge injection', 'RAG fine-tune']),
      t('AI για Εκπαίδευση: Εργαλεία και Στρατηγικές', 'AI εκπαιδευτικά εργαλεία', 'guide', 25, ['AI tutors', 'Khan Academy AI', 'personalized learning']),
      t('Μέλλον του Generative AI', 'μέλλον generative AI', 'analysis', 40, ['AGI', 'GPT-5', 'AI 2030']),
    ],
  },

  // ── 4. Κυβερνοασφάλεια ──────────────────────────────────────────────────────
  {
    name: 'Κυβερνοασφάλεια',
    slug: 'cybersecurity',
    pillarKeyword: 'κυβερνοασφάλεια',
    dbCategory: 'Τεχνολογία',
    description: 'Προστατέψτε τον εαυτό σας και την επιχείρησή σας online. Από phishing και ransomware έως VPN, 2FA και GDPR — ολοκληρωμένοι οδηγοί κυβερνοασφάλειας για χρήστες, επιχειρήσεις και επαγγελματίες IT που θέλουν να παραμείνουν ασφαλείς στον ψηφιακό κόσμο.',
    topics: [
      t('Τι είναι η Κυβερνοασφάλεια', 'κυβερνοασφάλεια', 'what-is', 20, ['cybersecurity', 'ψηφιακή ασφάλεια', 'information security']),
      t('Οι 10 Πιο Συχνές Κυβερνοεπιθέσεις', 'τύποι κυβερνοεπιθέσεων', 'explainer', 30, ['phishing', 'ransomware', 'social engineering']),
      t('Τι είναι το Phishing: Αναγνώριση και Αποφυγή', 'phishing επίθεση', 'guide', 20, ['email phishing', 'spear phishing', 'online scams']),
      t('Τι είναι το Ransomware', 'ransomware', 'what-is', 30, ['malware', 'crypto ransomware', 'WannaCry']),
      t('Τι είναι το Malware: Τύποι και Προστασία', 'malware κακόβουλο λογισμικό', 'guide', 25, ['virus', 'trojan', 'spyware', 'antivirus']),
      t('Οδηγός Ασφαλών Κωδικών και Password Managers', 'ασφαλείς κωδικοί', 'guide', 15, ['password manager', 'strong password', '1Password Bitwarden']),
      t('Τι είναι το Two-Factor Authentication (2FA)', 'two factor authentication 2FA', 'guide', 15, ['MFA', 'authenticator app', 'account security']),
      t('Τι είναι το VPN και Πότε να το Χρησιμοποιείς', 'VPN τι είναι', 'guide', 20, ['virtual private network', 'privacy', 'online anonymity']),
      t('Τι είναι το Zero-Day Exploit', 'zero day exploit', 'explainer', 55, ['vulnerability', 'patch management', 'CVE']),
      t('Τι είναι το DDoS Attack', 'DDoS attack', 'explainer', 35, ['denial of service', 'botnet', 'mitigation']),
      t('Τι είναι το Social Engineering', 'social engineering', 'explainer', 30, ['human hacking', 'pretexting', 'psychological manipulation']),
      t('Τι είναι το Dark Web', 'dark web', 'what-is', 30, ['Tor', 'darknet', 'onion sites']),
      t('Τι είναι το Ethical Hacking και Penetration Testing', 'ethical hacking penetration testing', 'what-is', 45, ['white hat hacker', 'pentest', 'security assessment']),
      t('Τι είναι το GDPR: Πλήρης Οδηγός', 'GDPR κανονισμός', 'guide', 35, ['data protection', 'EU privacy', 'compliance']),
      t('Τι είναι το Firewall', 'firewall τείχος προστασίας', 'what-is', 25, ['network security', 'packet filtering', 'WAF']),
      t('Τι είναι το Data Breach', 'data breach παραβίαση δεδομένων', 'explainer', 30, ['data leak', 'incident response', 'GDPR notification']),
      t('Ασφάλεια WiFi: Πλήρης Οδηγός Προστασίας', 'ασφαλής WiFi', 'guide', 15, ['WPA3', 'router security', 'home network']),
      t('Τι είναι το Zero Trust Security', 'zero trust security', 'explainer', 55, ['never trust always verify', 'microsegmentation', 'identity-first']),
      t('Κυβερνοασφάλεια για Μικρές Επιχειρήσεις', 'κυβερνοασφάλεια επιχειρήσεις', 'guide', 30, ['SMB security', 'endpoint protection', 'security policy']),
      t('Τι είναι το Bug Bounty Program', 'bug bounty', 'what-is', 40, ['responsible disclosure', 'HackerOne', 'security research']),
      t('AI και Κυβερνοασφάλεια: Νέες Απειλές και Άμυνες', 'AI κυβερνοασφάλεια', 'analysis', 45, ['AI attacks', 'deepfakes security', 'automated threats']),
      t('Τι είναι το SSL/TLS και HTTPS', 'SSL TLS HTTPS', 'explainer', 25, ['encryption', 'certificate', 'secure connection']),
      t('Τι είναι το Man-in-the-Middle Attack', 'man in the middle attack MITM', 'explainer', 45, ['network interception', 'ARP spoofing', 'HTTPS importance']),
      t('Πώς να Αναγνωρίσεις Online Απάτες', 'online απάτες αναγνώριση', 'guide', 20, ['scam detection', 'fake websites', 'online fraud']),
      t('Τι είναι η Κρυπτογράφηση End-to-End', 'end to end encryption', 'explainer', 40, ['E2EE', 'Signal', 'WhatsApp encryption']),
    ],
  },

  // ── 5. Cloud Computing & DevOps ─────────────────────────────────────────────
  {
    name: 'Cloud & DevOps',
    slug: 'cloud-devops',
    pillarKeyword: 'cloud computing',
    dbCategory: 'Τεχνολογία',
    description: 'Κατακτήστε το Cloud Computing και τις DevOps πρακτικές. AWS vs Azure vs Google Cloud, Docker, Kubernetes, CI/CD pipelines και serverless architectures — ό,τι χρειάζεστε για να χτίσετε, να αναπτύξετε και να κλιμακώσετε σύγχρονες εφαρμογές στο νέφος.',
    topics: [
      t('Τι είναι το Cloud Computing', 'cloud computing', 'what-is', 25, ['νέφος', 'IaaS PaaS SaaS', 'AWS Azure']),
      t('AWS vs Azure vs Google Cloud: Σύγκριση 2024', 'AWS Azure Google Cloud σύγκριση', 'comparison', 50, ['cloud providers', 'pricing', 'services']),
      t('Τι είναι το Docker', 'Docker containers', 'what-is', 40, ['containerization', 'images', 'docker-compose']),
      t('Τι είναι το Kubernetes', 'Kubernetes', 'what-is', 55, ['container orchestration', 'pods', 'K8s']),
      t('Τι είναι το DevOps', 'DevOps', 'what-is', 35, ['development operations', 'collaboration', 'automation']),
      t('Τι είναι το CI/CD Pipeline', 'CI/CD pipeline', 'explainer', 50, ['continuous integration', 'continuous deployment', 'Jenkins GitHub Actions']),
      t('Τι είναι το Serverless Computing', 'serverless computing', 'what-is', 45, ['FaaS', 'AWS Lambda', 'functions']),
      t('Τι είναι το Edge Computing', 'edge computing', 'what-is', 50, ['IoT', 'latency', 'distributed computing']),
      t('Τι είναι η Microservices Architecture', 'microservices architecture', 'what-is', 55, ['API', 'loosely coupled', 'scalability']),
      t('Τι είναι το Infrastructure as Code (IaC)', 'infrastructure as code IaC', 'explainer', 55, ['Terraform', 'Ansible', 'automation']),
      t('Τι είναι το Site Reliability Engineering (SRE)', 'SRE site reliability engineering', 'what-is', 60, ['Google SRE', 'reliability', 'SLO SLA SLI']),
      t('Τι είναι το GitOps', 'GitOps', 'explainer', 55, ['Git workflow', 'ArgoCD', 'deployment']),
      t('Τι είναι το Load Balancing', 'load balancing', 'explainer', 40, ['traffic distribution', 'high availability', 'nginx']),
      t('Τι είναι το CDN (Content Delivery Network)', 'CDN content delivery network', 'what-is', 35, ['Cloudflare', 'static assets', 'latency reduction']),
      t('Multi-Cloud Strategy: Οφέλη και Προκλήσεις', 'multi-cloud strategy', 'guide', 50, ['vendor lock-in', 'hybrid cloud', 'cloud portability']),
      t('Τι είναι το FinOps: Cloud Cost Management', 'cloud cost management FinOps', 'guide', 50, ['AWS cost', 'cloud spending', 'optimization']),
      t('Τι είναι το Monitoring και Observability', 'monitoring observability DevOps', 'guide', 50, ['Prometheus', 'Grafana', 'logs metrics traces']),
      t('Τι είναι το API Gateway', 'API gateway', 'explainer', 45, ['API management', 'rate limiting', 'authentication']),
      t('Cloud Security Best Practices', 'cloud security best practices', 'guide', 50, ['IAM', 'encryption', 'shared responsibility']),
      t('Τι είναι το Database as a Service (DBaaS)', 'database as a service DBaaS', 'what-is', 45, ['managed database', 'RDS', 'MongoDB Atlas']),
      t('Τι είναι το Platform as a Service (PaaS)', 'PaaS platform as a service', 'what-is', 40, ['Heroku', 'cloud platform', 'application hosting']),
      t('Deployment Strategies: Blue-Green, Canary, Rolling', 'deployment strategies', 'explainer', 55, ['zero downtime', 'canary release', 'rollback']),
      t('Τι είναι το Service Mesh', 'service mesh', 'explainer', 65, ['Istio', 'microservices communication', 'traffic management']),
      t('Τι είναι το Container Registry', 'container registry', 'explainer', 50, ['Docker Hub', 'image storage', 'CI/CD']),
      t('Μέλλον του Cloud Computing', 'μέλλον cloud computing', 'analysis', 40, ['quantum cloud', 'edge AI', 'serverless trends']),
    ],
  },

  // ── 6. Digital Marketing ────────────────────────────────────────────────────
  {
    name: 'Digital Marketing',
    slug: 'digital-marketing',
    pillarKeyword: 'digital marketing',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Ο πλήρης οδηγός ψηφιακού μάρκετινγκ για επιχειρήσεις και επαγγελματίες. Content marketing, email marketing, affiliate marketing, marketing automation, CRO και performance marketing — στρατηγικές που φέρνουν αποτελέσματα και μετρήσιμο ROI.',
    topics: [
      t('Τι είναι το Digital Marketing', 'digital marketing', 'what-is', 20, ['ψηφιακό μάρκετινγκ', 'online marketing', 'channels']),
      t('Πώς να Δημιουργήσεις Digital Marketing Strategy', 'digital marketing στρατηγική', 'guide', 30, ['marketing plan', 'channels', 'KPIs']),
      t('Τι είναι το Content Marketing', 'content marketing', 'what-is', 25, ['blog', 'περιεχόμενο', 'inbound']),
      t('Τι είναι το Email Marketing', 'email marketing', 'guide', 25, ['newsletter', 'open rate', 'campaign']),
      t('Τι είναι το Affiliate Marketing', 'affiliate marketing', 'what-is', 25, ['commissions', 'passive income', 'affiliate programs']),
      t('Τι είναι το Influencer Marketing', 'influencer marketing', 'guide', 25, ['nano influencers', 'UGC', 'brand deals']),
      t('Τι είναι το Performance Marketing', 'performance marketing', 'what-is', 40, ['ROI', 'CPA', 'data-driven']),
      t('Τι είναι το Marketing Automation', 'marketing automation', 'what-is', 40, ['HubSpot', 'email sequences', 'lead nurturing']),
      t('Τι είναι το Conversion Rate Optimization (CRO)', 'CRO conversion rate optimization', 'guide', 45, ['landing pages', 'A/B testing', 'UX']),
      t('Τι είναι το A/B Testing στο Marketing', 'A/B testing marketing', 'explainer', 35, ['split testing', 'hypothesis', 'statistical significance']),
      t('Τι είναι το Customer Journey Mapping', 'customer journey mapping', 'guide', 35, ['touchpoints', 'awareness consideration decision', 'CX']),
      t('Τι είναι το Buyer Persona', 'buyer persona', 'guide', 25, ['ideal customer', 'target audience', 'demographics']),
      t('Τι είναι το Marketing Funnel', 'marketing funnel', 'explainer', 30, ['TOFU MOFU BOFU', 'awareness', 'conversion']),
      t('Τι είναι το Brand Storytelling', 'storytelling marketing', 'guide', 30, ['brand narrative', 'emotional marketing', 'Nike storytelling']),
      t('Τι είναι το Viral Marketing', 'viral marketing', 'explainer', 30, ['viral content', 'word of mouth', 'sharing mechanics']),
      t('Τι είναι το Retargeting', 'retargeting remarketing', 'explainer', 35, ['Facebook pixel', 'remarketing', 'ad frequency']),
      t('Τι είναι το PPC Advertising', 'PPC pay per click', 'what-is', 35, ['Google Ads', 'CPC', 'bidding']),
      t('Τι είναι το Marketing Analytics', 'marketing analytics', 'guide', 40, ['Google Analytics', 'attribution', 'ROAS']),
      t('Τι είναι το Omnichannel Marketing', 'omnichannel marketing', 'explainer', 40, ['multichannel', 'consistent experience', 'customer-centric']),
      t('Πώς να Μετράς ROI στο Digital Marketing', 'ROI digital marketing', 'guide', 35, ['return on investment', 'attribution models', 'analytics']),
      t('AI στο Digital Marketing: Εφαρμογές και Εργαλεία', 'AI digital marketing', 'guide', 35, ['AI ads', 'programmatic', 'personalization AI']),
      t('Τι είναι το Growth Marketing', 'growth marketing', 'what-is', 40, ['growth loops', 'experimentation', 'product marketing']),
      t('Τι είναι το Inbound vs Outbound Marketing', 'inbound outbound marketing', 'comparison', 25, ['pull push marketing', 'cold calls vs SEO', 'strategy']),
      t('Τι είναι το Customer Retention Marketing', 'customer retention marketing', 'guide', 35, ['loyalty programs', 'churn reduction', 'CLV']),
      t('Τα Καλύτερα Marketing Tools 2024', 'καλύτερα marketing tools', 'best-of', 20, ['HubSpot', 'Mailchimp', 'Semrush', 'marketing software']),
    ],
  },

  // ── 7. SEO & Content Strategy ───────────────────────────────────────────────
  {
    name: 'SEO',
    slug: 'seo',
    pillarKeyword: 'SEO',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Κατακτήστε τις πρώτες θέσεις της Google με αποδεδειγμένες SEO στρατηγικές. On-page SEO, technical SEO, link building, keyword research, Core Web Vitals και E-E-A-T — αναλυτικοί οδηγοί για website owners, bloggers και digital marketers που θέλουν organic traffic.',
    topics: [
      t('Τι είναι το SEO: Πλήρης Οδηγός', 'SEO τι είναι', 'guide', 20, ['search engine optimization', 'Google ranking', 'organic traffic']),
      t('On-Page SEO: Πλήρης Οδηγός Βελτιστοποίησης', 'on page SEO', 'guide', 35, ['title tags', 'meta description', 'keyword optimization']),
      t('Off-Page SEO: Link Building και Αυθεντικότητα', 'off page SEO', 'guide', 40, ['backlinks', 'domain authority', 'guest posting']),
      t('Technical SEO: Ο Πλήρης Οδηγός', 'technical SEO', 'guide', 55, ['site speed', 'crawlability', 'structured data']),
      t('Keyword Research: Πώς να Βρεις τις Σωστές Λέξεις-Κλειδιά', 'keyword research', 'tutorial', 35, ['Ahrefs', 'SEMrush', 'search volume']),
      t('Τι είναι το Link Building', 'link building', 'guide', 45, ['backlinks', 'outreach', 'domain authority']),
      t('Core Web Vitals: Οδηγός Βελτιστοποίησης', 'Core Web Vitals', 'guide', 45, ['LCP FID CLS', 'page experience', 'PageSpeed']),
      t('Local SEO: Πώς να Κατατάσσεσαι Τοπικά', 'local SEO', 'guide', 35, ['Google My Business', 'local citations', 'NAP']),
      t('Τι είναι το Search Intent', 'search intent SEO', 'explainer', 40, ['informational', 'commercial', 'transactional']),
      t('Τι είναι το E-E-A-T στο Google', 'E-E-A-T SEO', 'explainer', 45, ['expertise authority trust', 'Google quality', 'content quality']),
      t('Τι είναι τα Featured Snippets', 'featured snippets', 'guide', 40, ['position zero', 'rich results', 'FAQ schema']),
      t('Long-tail Keywords: Γιατί Είναι Χρυσός', 'long tail keywords', 'explainer', 30, ['low competition', 'specific intent', 'niche keywords']),
      t('Pillar Pages και Topic Clusters για SEO', 'pillar pages topic clusters', 'guide', 45, ['content hub', 'internal linking', 'semantic SEO']),
      t('Τι είναι το Schema Markup', 'schema markup structured data', 'guide', 50, ['JSON-LD', 'rich snippets', 'schema.org']),
      t('Τι είναι το Canonical URL', 'canonical URL', 'explainer', 45, ['duplicate content', 'rel canonical', 'SEO consolidation']),
      t('Τι είναι το Crawl Budget', 'crawl budget', 'explainer', 60, ['Googlebot', 'crawl efficiency', 'robots.txt']),
      t('Πώς να Φτιάξεις XML Sitemap', 'sitemap XML', 'tutorial', 30, ['sitemap.xml', 'Google Search Console', 'indexation']),
      t('Τι είναι το Domain Authority', 'domain authority', 'explainer', 35, ['Moz DA', 'backlinks', 'trustworthiness']),
      t('SEO για Mobile: Mobile-First Indexing', 'mobile SEO', 'guide', 35, ['responsive design', 'mobile-first', 'AMP']),
      t('Voice Search SEO: Πώς να Βελτιστοποιείς', 'voice search SEO', 'guide', 40, ['Siri Alexa Google', 'conversational queries', 'featured snippets']),
      t('Τα Καλύτερα SEO Tools Συγκριτικά', 'SEO tools σύγκριση', 'best-of', 30, ['Ahrefs SEMrush Moz', 'Google Search Console', 'Screaming Frog']),
      t('Τι είναι το Duplicate Content', 'duplicate content SEO', 'explainer', 40, ['thin content', 'canonical', 'Google penalty']),
      t('Πώς να Κάνεις SEO Audit', 'SEO audit', 'tutorial', 40, ['site analysis', 'technical issues', 'content gaps']),
      t('Τι είναι το Page Authority', 'page authority SEO', 'explainer', 40, ['link juice', 'internal links', 'Moz']),
      t('Μέλλον του SEO: AI, SGE και Τάσεις', 'μέλλον SEO', 'analysis', 40, ['Google SGE', 'AI search', 'search generative experience']),
    ],
  },

  // ── 8. Social Media Marketing ───────────────────────────────────────────────
  {
    name: 'Social Media',
    slug: 'social-media',
    pillarKeyword: 'social media marketing',
    dbCategory: 'Τεχνολογία',
    description: 'Κατανοήστε τους αλγόριθμους και χτίστε παρουσία στα social media. Instagram, Facebook, TikTok, LinkedIn, YouTube — αλγόριθμοι, content strategy, viral marketing και social media advertising για επιχειρήσεις και δημιουργούς περιεχομένου.',
    topics: [
      t('Τι είναι το Social Media Marketing', 'social media marketing', 'what-is', 20, ['SMM', 'organic reach', 'social channels']),
      t('Αλγόριθμος Instagram 2024: Πώς Λειτουργεί', 'αλγόριθμος Instagram', 'explainer', 30, ['Instagram reach', 'Reels', 'engagement signals']),
      t('Αλγόριθμος Facebook 2024', 'αλγόριθμος Facebook', 'explainer', 30, ['organic reach', 'EdgeRank', 'news feed']),
      t('Αλγόριθμος TikTok: For You Page', 'αλγόριθμος TikTok', 'explainer', 25, ['FYP', 'TikTok reach', 'video completion']),
      t('Αλγόριθμος LinkedIn: Πώς να Αυξήσεις Reach', 'αλγόριθμος LinkedIn', 'explainer', 30, ['LinkedIn organic', 'professional content', 'dwell time']),
      t('Αλγόριθμος YouTube: Πώς Κατατάσσονται Βίντεο', 'αλγόριθμος YouTube', 'explainer', 30, ['YouTube SEO', 'watch time', 'CTR']),
      t('Τι είναι το Engagement Rate', 'engagement rate social media', 'explainer', 25, ['likes comments shares', 'reach', 'interaction']),
      t('Πώς να Δημιουργείς Viral Content', 'viral content δημιουργία', 'guide', 30, ['shareability', 'emotional triggers', 'hooks']),
      t('Social Media Analytics: Πλήρης Οδηγός', 'social media analytics', 'guide', 35, ['metrics', 'insights', 'performance tracking']),
      t('Τι είναι το User-Generated Content (UGC)', 'UGC user generated content', 'what-is', 25, ['authentic content', 'social proof', 'brand advocacy']),
      t('Hashtag Strategy: Πώς να Επιλέγεις Hashtags', 'hashtag strategy', 'guide', 20, ['hashtag research', 'niche hashtags', 'trending hashtags']),
      t('Influencer Marketing για Μικρές Επιχειρήσεις', 'influencer marketing μικρές επιχειρήσεις', 'guide', 25, ['micro influencers', 'budget', 'ROI']),
      t('Short-Form Video Strategy: Reels, TikTok, Shorts', 'short form video strategy', 'guide', 25, ['Reels TikTok Shorts', 'hooks', '60 seconds']),
      t('Social Media Advertising: Πλήρης Οδηγός', 'social media advertising', 'guide', 35, ['Facebook Ads', 'Instagram Ads', 'targeting']),
      t('Τι είναι το Community Building Online', 'community building online', 'guide', 30, ['Discord', 'Facebook Groups', 'engagement']),
      t('Content Calendar: Πώς να Οργανώσεις Social Media', 'content calendar social media', 'guide', 25, ['planning', 'scheduling', 'Buffer Hootsuite']),
      t('Brand Voice on Social Media', 'brand voice social media', 'guide', 30, ['tone of voice', 'consistency', 'brand identity']),
      t('Social Media Crisis Management', 'social media crisis management', 'guide', 35, ['reputation', 'damage control', 'communication']),
      t('Πώς να Αυξήσεις Followers Organically', 'αύξηση followers', 'guide', 20, ['organic growth', 'consistency', 'value content']),
      t('Social Listening: Τι Λένε για εσένα Online', 'social listening', 'what-is', 35, ['brand monitoring', 'Mention', 'sentiment analysis']),
      t('Podcast Marketing: Πώς να Αναπτύξεις Ακροατήριο', 'podcast marketing', 'guide', 30, ['podcast growth', 'Spotify', 'Apple Podcasts']),
      t('Newsletter Marketing: Πώς να Χτίσεις Λίστα', 'newsletter marketing', 'guide', 25, ['email list building', 'Substack', 'ConvertKit']),
      t('Live Streaming Strategy για Επιχειρήσεις', 'live streaming strategy', 'guide', 30, ['Facebook Live', 'YouTube Live', 'Twitch']),
      t('Cross-Platform Social Media Strategy', 'cross platform social media', 'guide', 35, ['omnichannel', 'repurposing', 'content distribution']),
      t('Social Commerce: Αγορές Μέσω Social Media', 'social commerce', 'what-is', 30, ['Instagram shopping', 'TikTok shop', 'Facebook marketplace']),
    ],
  },

  // ── 9. Business Strategy ────────────────────────────────────────────────────
  {
    name: 'Business Strategy',
    slug: 'business-strategy',
    pillarKeyword: 'επιχειρηματική στρατηγική',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Επιχειρηματική στρατηγική για managers, entrepreneurs και στελέχη. Business Model Canvas, SWOT, OKR, KPI, Blue Ocean Strategy, Porter\'s Five Forces — τα εργαλεία και frameworks που οδηγούν σε βιώσιμη ανάπτυξη και ανταγωνιστικό πλεονέκτημα.',
    topics: [
      t('Τι είναι το Business Model Canvas', 'business model canvas', 'guide', 30, ['value proposition', 'revenue streams', 'key activities']),
      t('SWOT Analysis: Πλήρης Οδηγός', 'SWOT ανάλυση', 'guide', 25, ['strengths weaknesses', 'opportunities threats', 'strategic planning']),
      t('Τι είναι τα OKR', 'OKR objectives key results', 'guide', 35, ['Google OKR', 'goal setting', 'performance']),
      t('Τι είναι τα KPI', 'KPI key performance indicators', 'guide', 30, ['metrics', 'performance measurement', 'dashboard']),
      t('Τι είναι το Lean Management', 'lean management', 'explainer', 40, ['waste elimination', 'Toyota', 'efficiency']),
      t('Blue Ocean Strategy: Δημιούργησε Αδιαμφισβήτητη Αγορά', 'blue ocean strategy', 'explainer', 45, ['uncontested market', 'value innovation', 'competition irrelevant']),
      t('Porter\'s Five Forces: Ανάλυση Ανταγωνισμού', 'porter five forces', 'explainer', 45, ['competitive forces', 'industry analysis', 'Porter model']),
      t('Τι είναι η Competitive Analysis', 'competitive analysis', 'guide', 35, ['competitor research', 'market positioning', 'SWOT competitor']),
      t('Τι είναι η Αξία Προτάσεως (Value Proposition)', 'value proposition', 'guide', 35, ['customer value', 'differentiation', 'unique selling proposition']),
      t('Pricing Strategy: Πώς να Τιμολογείς Σωστά', 'pricing strategy', 'guide', 40, ['cost-based', 'value-based', 'competitive pricing']),
      t('Τι είναι το Customer Retention', 'customer retention', 'guide', 35, ['loyalty', 'churn', 'CLV']),
      t('Cash Flow Management: Οδηγός Επιβίωσης', 'cash flow management', 'guide', 40, ['ταμειακή ροή', 'working capital', 'forecasting']),
      t('Τι είναι το Business Intelligence', 'business intelligence', 'what-is', 40, ['BI tools', 'data visualization', 'Power BI Tableau']),
      t('Τι είναι το Risk Management', 'risk management', 'guide', 40, ['risk assessment', 'mitigation', 'contingency planning']),
      t('Τι είναι η Εταιρική Κουλτούρα', 'εταιρική κουλτούρα', 'analysis', 30, ['company culture', 'values', 'employee engagement']),
      t('Τι είναι το ESG για Επιχειρήσεις', 'ESG επιχειρήσεις', 'what-is', 35, ['environmental social governance', 'sustainability', 'impact investing']),
      t('Τι είναι η Εταιρική Κοινωνική Ευθύνη (CSR)', 'CSR εταιρική κοινωνική ευθύνη', 'what-is', 30, ['sustainability', 'corporate responsibility', 'community']),
      t('Τι είναι το Due Diligence', 'due diligence', 'what-is', 40, ['M&A', 'investment', 'risk assessment']),
      t('Τι είναι τα M&A (Mergers and Acquisitions)', 'mergers acquisitions M&A', 'what-is', 45, ['συγχωνεύσεις', 'acquisition', 'deal structure']),
      t('Πώς να Φτιάξεις Business Plan', 'business plan', 'guide', 30, ['executive summary', 'financial projections', 'market analysis']),
      t('Τι είναι το Market Segmentation', 'market segmentation', 'guide', 35, ['demographics', 'psychographics', 'target market']),
      t('Δεδομένα και Αποφάσεις: Data-Driven Strategy', 'data driven decisions', 'guide', 40, ['analytics', 'evidence-based', 'KPIs']),
      t('Τι είναι το Platform Business Model', 'platform business model', 'what-is', 40, ['marketplace', 'network effects', 'Amazon Uber']),
      t('Τι είναι το Break-Even Analysis', 'break even analysis', 'guide', 40, ['fixed costs', 'variable costs', 'profitability']),
      t('Στρατηγικός Σχεδιασμός: Από Όραμα σε Δράση', 'strategic planning', 'guide', 40, ['strategy execution', 'roadmap', 'vision mission']),
    ],
  },

  // ── 10. Startups ─────────────────────────────────────────────────────────────
  {
    name: 'Startups',
    slug: 'startups',
    pillarKeyword: 'startup',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Από ιδέα σε startup — ο πλήρης οδηγός για επιχειρηματίες. MVP, product-market fit, bootstrapping vs VC, pitch deck, growth hacking και startup metrics — ό,τι χρειάζεστε για να χτίσετε, να χρηματοδοτήσετε και να αναπτύξετε ένα επιτυχημένο startup.',
    topics: [
      t('Τι είναι Startup', 'τι είναι startup', 'what-is', 20, ['innovation', 'scalable', 'technology']),
      t('Πώς να Ξεκινήσεις Startup από Μηδέν', 'πώς να ξεκινήσεις startup', 'guide', 25, ['idea validation', 'co-founder', 'first steps']),
      t('Τι είναι το MVP (Minimum Viable Product)', 'MVP minimum viable product', 'what-is', 30, ['lean startup', 'fast validation', 'build measure learn']),
      t('Τι είναι το Lean Startup Methodology', 'lean startup', 'explainer', 35, ['Eric Ries', 'pivot', 'validated learning']),
      t('Τι είναι το Product-Market Fit', 'product market fit', 'explainer', 40, ['PMF', 'retention', 'market pull']),
      t('Τι είναι το Bootstrapping', 'bootstrapping startup', 'what-is', 30, ['self-funded', 'no investors', 'profitable']),
      t('Τι είναι το Angel Investing', 'angel investing', 'what-is', 35, ['angel investors', 'seed stage', 'equity']),
      t('Τι είναι το Venture Capital', 'venture capital', 'what-is', 35, ['VC funds', 'portfolio', 'LP GP']),
      t('Τι είναι το Seed Funding', 'seed funding', 'what-is', 35, ['pre-seed seed', 'angel', 'first round']),
      t('Τι είναι το Series A B C Funding', 'Series A B C funding', 'explainer', 40, ['growth rounds', 'valuation', 'VC']),
      t('Τι είναι τα Startup Accelerators και Incubators', 'startup accelerators incubators', 'what-is', 30, ['Y Combinator', '500 Startups', 'cohort']),
      t('Πώς να Κάνεις Pitch σε Επενδυτές', 'startup pitch investors', 'guide', 35, ['pitch deck', 'elevator pitch', 'storytelling']),
      t('Τι είναι το Growth Hacking', 'growth hacking', 'what-is', 35, ['viral loops', 'referral programs', 'retention']),
      t('Τι είναι το Churn Rate', 'churn rate', 'explainer', 35, ['customer loss', 'retention', 'SaaS']),
      t('MRR και ARR: Τα Βασικά SaaS Metrics', 'MRR ARR startup metrics', 'explainer', 35, ['monthly recurring revenue', 'annual revenue', 'growth']),
      t('Τι είναι το CAC και LTV', 'CAC LTV customer acquisition', 'explainer', 40, ['acquisition cost', 'lifetime value', 'unit economics']),
      t('Τι είναι το Burn Rate', 'burn rate startup', 'what-is', 35, ['cash burn', 'runway', 'monthly expenses']),
      t('Πώς να Βρεις Co-founder', 'co-founder startup', 'guide', 30, ['co-founder search', 'equity split', 'skills complementary']),
      t('Τι είναι το Unicorn Startup', 'unicorn startup', 'what-is', 20, ['$1B valuation', 'decacorn', 'private companies']),
      t('Τι είναι το Product-Led Growth (PLG)', 'product led growth PLG', 'explainer', 45, ['freemium', 'self-serve', 'Slack Dropbox']),
      t('Τι είναι το Pivot', 'pivot startup', 'explainer', 35, ['strategic change', 'Instagram YouTube', 'pivot examples']),
      t('Τι είναι το Exit Strategy', 'exit strategy startup', 'guide', 45, ['IPO', 'acquisition', 'merger']),
      t('Startup Valuation: Πώς Αξιολογείται μια Startup', 'startup valuation', 'guide', 45, ['pre-money post-money', 'DCF', 'comparable multiples']),
      t('Πώς να Χτίσεις Startup Team', 'startup team building', 'guide', 30, ['hiring', 'equity', 'culture']),
      t('Startup Metrics: Ποια Νούμερα Μετράνε', 'startup metrics', 'guide', 40, ['north star metric', 'actionable metrics', 'vanity metrics']),
    ],
  },

  // ── 11. Παραγωγικότητα ───────────────────────────────────────────────────────
  {
    name: 'Παραγωγικότητα',
    slug: 'productivity',
    pillarKeyword: 'παραγωγικότητα',
    dbCategory: 'Τεχνολογία',
    description: 'Αυξήστε την παραγωγικότητά σας με αποδεδειγμένες μεθόδους και εργαλεία. Pomodoro, Deep Work, GTD, Time Blocking, Eisenhower Matrix και PKM — πρακτικές τεχνικές για να κάνετε περισσότερα σε λιγότερο χρόνο, χωρίς burnout.',
    topics: [
      t('Πώς να Αυξήσεις Παραγωγικότητα', 'αύξηση παραγωγικότητας', 'guide', 20, ['productivity tips', 'time management', 'efficiency']),
      t('Τεχνική Pomodoro: Πλήρης Οδηγός', 'τεχνική Pomodoro', 'guide', 15, ['25 minutes focus', 'breaks', 'time management']),
      t('Τι είναι το Deep Work', 'deep work Cal Newport', 'what-is', 25, ['focused work', 'distraction-free', 'concentration']),
      t('Τι είναι το Time Blocking', 'time blocking', 'guide', 20, ['calendar blocking', 'schedule', 'productivity method']),
      t('Τι είναι η μέθοδος GTD (Getting Things Done)', 'GTD getting things done', 'guide', 30, ['David Allen', 'inbox zero', 'next action']),
      t('Πώς να Ξεπεράσεις Αναβλητικότητα', 'αναβλητικότητα', 'guide', 15, ['procrastination', 'motivation', 'action bias']),
      t('Τι είναι το Flow State', 'flow state κατάσταση ροής', 'what-is', 30, ['Csikszentmihalyi', 'peak performance', 'engagement']),
      t('Τι είναι το Eisenhower Matrix', 'Eisenhower matrix προτεραιότητες', 'guide', 20, ['urgent important', 'priority matrix', 'task management']),
      t('Τι είναι το Inbox Zero', 'inbox zero email', 'guide', 20, ['email management', 'declutter', 'GTD']),
      t('Τι είναι το Personal Knowledge Management (PKM)', 'personal knowledge management PKM', 'guide', 35, ['Obsidian', 'Notion', 'second brain']),
      t('Τι είναι το Second Brain (Zettelkasten)', 'second brain Zettelkasten', 'guide', 30, ['note-taking', 'knowledge system', 'Tiago Forte']),
      t('Τα Καλύτερα Productivity Apps', 'καλύτερα productivity apps', 'best-of', 15, ['Notion Todoist', 'Things 3', 'task management apps']),
      t('Τι είναι το Single-Tasking vs Multitasking', 'single tasking vs multitasking', 'analysis', 20, ['focus', 'cognitive switching', 'efficiency']),
      t('Αρχή Pareto 80/20: Πώς να την Εφαρμόζεις', 'αρχή Pareto 80 20', 'explainer', 20, ['Pareto principle', 'high leverage', 'efficiency']),
      t('SMART Goals: Πώς να Θέτεις Στόχους', 'SMART goals στόχοι', 'guide', 15, ['specific measurable', 'attainable', 'goal setting']),
      t('Τι είναι το Kanban Method', 'kanban method', 'guide', 25, ['visual workflow', 'WIP limits', 'Trello']),
      t('Batch Processing: Η Τεχνική για Μαζική Αποδοτικότητα', 'batch processing εργασίες', 'guide', 20, ['task batching', 'context switching', 'efficiency']),
      t('Πώς να Κάνεις Αποτελεσματικές Συναντήσεις', 'αποτελεσματικές συναντήσεις', 'guide', 25, ['meeting agenda', 'async meetings', 'meeting-free days']),
      t('Πώς να Λαμβάνεις Καλύτερες Αποφάσεις', 'λήψη αποφάσεων', 'guide', 30, ['decision frameworks', 'mental models', '10-10-10 rule']),
      t('Τι είναι το No-Code Workflow Automation', 'no-code workflow automation', 'guide', 30, ['Zapier', 'Make', 'automation']),
      t('Πώς να Διαχειριστείς Email Αποτελεσματικά', 'email management', 'guide', 20, ['email filters', 'templates', 'inbox management']),
      t('Τι είναι το Mind Mapping', 'mind mapping', 'what-is', 20, ['brainstorming', 'visual thinking', 'MindMeister']),
      t('Ψηφιακό Detox: Πώς να Μειώσεις Οθόνη', 'ψηφιακό detox', 'guide', 20, ['screen time', 'digital wellness', 'phone addiction']),
      t('Πώς να Χτίσεις Productive Πρωινή Ρουτίνα', 'πρωινή ρουτίνα παραγωγικότητα', 'guide', 15, ['morning routine', 'habits', 'discipline']),
      t('Τι είναι το Asynchronous Work', 'asynchronous work async', 'what-is', 25, ['remote work', 'Basecamp', 'async communication']),
    ],
  },

  // ── 12. Καριέρα ─────────────────────────────────────────────────────────────
  {
    name: 'Καριέρα',
    slug: 'career',
    pillarKeyword: 'καριέρα',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Αναπτύξτε την καριέρα σας με επαγγελματικές στρατηγικές. Βιογραφικό, συνέντευξη, personal branding, networking, soft skills, freelancing και LinkedIn — πρακτικοί οδηγοί για επαγγελματίες που θέλουν να εξελιχθούν και να ανοίξουν νέους ορίζοντες.',
    topics: [
      t('Πώς να Γράψεις Βιογραφικό που Ξεχωρίζει', 'βιογραφικό σημείωμα', 'guide', 15, ['CV tips', 'ATS', 'resume writing']),
      t('Πώς να Ετοιμαστείς για Συνέντευξη Εργασίας', 'συνέντευξη εργασίας', 'guide', 15, ['STAR method', 'common questions', 'preparation']),
      t('Τι είναι το Personal Branding', 'personal branding', 'guide', 25, ['LinkedIn', 'thought leadership', 'online presence']),
      t('Πώς να Ζητήσεις Αύξηση Μισθού', 'αύξηση μισθού', 'guide', 25, ['salary negotiation', 'market rate', 'BATNA']),
      t('Τι είναι το Burnout: Αναγνώριση και Πρόληψη', 'burnout επαγγελματική εξουθένωση', 'guide', 20, ['work stress', 'exhaustion', 'recovery']),
      t('Πώς να Αλλάξεις Καριέρα Επιτυχώς', 'αλλαγή καριέρας', 'guide', 25, ['career pivot', 'transferable skills', 'reskilling']),
      t('Τι είναι τα Soft Skills', 'soft skills δεξιότητες', 'what-is', 20, ['communication', 'teamwork', 'emotional intelligence']),
      t('Hard Skills vs Soft Skills', 'hard skills vs soft skills', 'comparison', 20, ['technical skills', 'interpersonal skills', 'HR']),
      t('Τι είναι το Career Coaching', 'career coaching', 'what-is', 25, ['coach', 'career direction', 'professional development']),
      t('Πώς να Χτίσεις Professional Network', 'professional networking', 'guide', 20, ['LinkedIn', 'events', 'relationships']),
      t('LinkedIn: Πλήρης Οδηγός για Καριέρα', 'LinkedIn καριέρα οδηγός', 'guide', 20, ['LinkedIn profile', 'connections', 'job search']),
      t('Τι είναι το Freelancing', 'freelancing ελεύθερος επαγγελματίας', 'what-is', 20, ['self-employed', 'gig economy', 'independence']),
      t('Πώς να Γίνεις Επιτυχημένος Freelancer', 'πώς να γίνεις freelancer', 'guide', 20, ['clients', 'rates', 'platforms']),
      t('Τι είναι το Upskilling και Reskilling', 'upskilling reskilling', 'explainer', 25, ['continuous learning', 'new skills', 'future-proof']),
      t('Πώς να Μάθεις Online Δεξιότητες', 'online learning δεξιότητες', 'guide', 15, ['Udemy Coursera', 'self-paced', 'certificates']),
      t('Τι είναι το Work-Life Balance', 'work life balance', 'guide', 15, ['wellbeing', 'boundaries', 'mental health']),
      t('Πώς να Διαχειριστείς Δύσκολους Συναδέλφους', 'δύσκολοι συνάδελφοι', 'guide', 20, ['conflict resolution', 'communication', 'workplace']),
      t('Τι είναι τα Transferable Skills', 'transferable skills', 'explainer', 25, ['universal skills', 'career change', 'adaptability']),
      t('Τι είναι το Emotional Intelligence στην Εργασία', 'emotional intelligence εργασία', 'what-is', 25, ['EQ', 'empathy', 'self-awareness']),
      t('Πώς να Παρουσιάζεις με Αυτοπεποίθηση', 'public speaking τεχνικές', 'guide', 25, ['presentation skills', 'body language', 'storytelling']),
      t('Τι είναι το Mentoring', 'mentoring', 'what-is', 20, ['mentor mentee', 'guidance', 'career development']),
      t('Τα Καλύτερα Sites Αναζήτησης Εργασίας', 'αναζήτηση εργασίας online', 'best-of', 15, ['LinkedIn Jobs', 'Kariera', 'Indeed']),
      t('Πώς να Γίνεις Αναντικατάστατος στη Δουλειά σου', 'αναντικατάστατος υπάλληλος', 'guide', 25, ['value creation', 'skills', 'visibility']),
      t('Τι είναι τα Transferable Skills', 'μεταβιβάσιμες δεξιότητες', 'explainer', 25, ['career change', 'adaptable skills', 'resume']),
      t('Διά Βίου Μάθηση: Γιατί Είναι Απαραίτητη', 'διά βίου μάθηση', 'analysis', 20, ['lifelong learning', 'adaptability', 'growth mindset']),
    ],
  },

  // ── 13. E-commerce ──────────────────────────────────────────────────────────
  {
    name: 'E-commerce',
    slug: 'ecommerce',
    pillarKeyword: 'e-commerce',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Δημιουργήστε και αναπτύξτε το ηλεκτρονικό σας κατάστημα. Shopify vs WooCommerce, dropshipping, e-commerce SEO, conversion optimization, email marketing και logistics — ολοκληρωμένοι οδηγοί για online επιχειρηματίες που θέλουν βιώσιμες πωλήσεις.',
    topics: [
      t('Τι είναι το E-commerce', 'e-commerce', 'what-is', 20, ['online store', 'ψηφιακό εμπόριο', 'online sales']),
      t('Πώς να Ξεκινήσεις Online Store', 'online store ξεκίνημα', 'guide', 25, ['e-commerce setup', 'platform', 'first sale']),
      t('Τι είναι το Dropshipping', 'dropshipping', 'what-is', 25, ['no inventory', 'supplier', 'Aliexpress']),
      t('Shopify vs WooCommerce: Ποιο να Επιλέξεις', 'Shopify WooCommerce σύγκριση', 'comparison', 30, ['e-commerce platform', 'pricing', 'features']),
      t('E-commerce SEO: Πώς να Κατατάσσεις Προϊόντα', 'e-commerce SEO', 'guide', 40, ['product pages', 'category SEO', 'schema products']),
      t('Τι είναι το Cart Abandonment', 'cart abandonment', 'guide', 35, ['abandoned cart emails', 'recovery', 'checkout optimization']),
      t('Τι είναι το Cross-selling και Upselling', 'cross selling upselling e-commerce', 'guide', 30, ['product recommendations', 'AOV', 'revenue increase']),
      t('E-commerce Conversion Rate Optimization', 'e-commerce conversion rate', 'guide', 40, ['checkout UX', 'product photos', 'trust signals']),
      t('Τι είναι το Fulfillment', 'e-commerce fulfillment', 'what-is', 30, ['order fulfillment', '3PL', 'logistics']),
      t('Payment Methods για E-commerce', 'e-commerce payment methods', 'guide', 25, ['Stripe', 'PayPal', 'credit card', 'Viva Wallet']),
      t('Τι είναι το Social Commerce', 'social commerce', 'what-is', 30, ['Instagram shopping', 'TikTok shop', 'Facebook marketplace']),
      t('Τι είναι το Mobile Commerce (m-Commerce)', 'm-commerce mobile commerce', 'what-is', 25, ['mobile shopping', 'app commerce', 'responsive store']),
      t('Email Marketing για E-commerce', 'e-commerce email marketing', 'guide', 30, ['welcome series', 'abandoned cart', 'post-purchase']),
      t('E-commerce Analytics: Ποια Metrics Μετράνε', 'e-commerce analytics', 'guide', 35, ['conversion rate', 'AOV', 'ROAS']),
      t('Τι είναι το Return Policy', 'e-commerce return policy', 'guide', 25, ['returns', 'customer trust', 'reverse logistics']),
      t('Τι είναι το Customer Lifetime Value στο E-commerce', 'CLV e-commerce', 'explainer', 35, ['repeat purchase', 'loyalty', 'retention']),
      t('Amazon Marketplace: Πώς να Πουλάς', 'amazon marketplace seller', 'guide', 35, ['FBA', 'product listing', 'Amazon SEO']),
      t('Τι είναι το Print-on-Demand', 'print on demand', 'what-is', 25, ['POD', 'Printful', 'custom products']),
      t('Τι είναι το Product Photography', 'product photography e-commerce', 'guide', 25, ['product photos', 'white background', 'conversion']),
      t('Τι είναι το Marketplace Strategy', 'marketplace strategy e-commerce', 'guide', 35, ['multichannel', 'marketplace fees', 'visibility']),
      t('Πώς να Γράφεις Product Descriptions', 'product description SEO', 'guide', 30, ['copywriting', 'benefits features', 'keywords']),
      t('Customer Reviews: Πώς να Αυξήσεις και Διαχειριστείς', 'customer reviews e-commerce', 'guide', 25, ['social proof', 'Trustpilot', 'review management']),
      t('E-commerce Logistics: Αποστολές και Παράδοση', 'e-commerce logistics', 'guide', 35, ['shipping', 'courier', 'delivery time']),
      t('Τι είναι το Headless Commerce', 'headless commerce', 'what-is', 55, ['decoupled front-end', 'API-first', 'Shopify headless']),
      t('Τάσεις E-commerce: Τι Έρχεται', 'e-commerce trends', 'analysis', 30, ['AR shopping', 'sustainability', 'AI commerce']),
    ],
  },

  // ── 14. Fintech & Crypto ─────────────────────────────────────────────────────
  {
    name: 'Fintech & Crypto',
    slug: 'fintech-crypto',
    pillarKeyword: 'fintech',
    dbCategory: 'Οικονομία',
    description: 'Κατανοήστε το μέλλον των χρημάτων. Blockchain, Bitcoin, DeFi, Web3, smart contracts, digital banking και ρύθμιση crypto — αντικειμενικοί και αναλυτικοί οδηγοί για επενδυτές, επαγγελματίες fintech και όποιον θέλει να καταλάβει τις τεχνολογίες που αναδιαμορφώνουν τα οικονομικά.',
    topics: [
      t('Τι είναι το Fintech', 'fintech', 'what-is', 30, ['financial technology', 'digital finance', 'banking apps']),
      t('Τι είναι το Blockchain', 'blockchain τεχνολογία', 'what-is', 40, ['distributed ledger', 'immutable', 'consensus']),
      t('Τι είναι το Bitcoin', 'Bitcoin', 'what-is', 25, ['cryptocurrency', 'Satoshi Nakamoto', 'digital gold']),
      t('Τι είναι τα Κρυπτονομίσματα', 'κρυπτονομίσματα', 'what-is', 25, ['crypto', 'altcoins', 'blockchain']),
      t('Τι είναι τα NFTs', 'NFT', 'what-is', 30, ['non-fungible tokens', 'digital art', 'ownership']),
      t('Τι είναι το Ethereum', 'Ethereum', 'what-is', 30, ['smart contracts', 'ETH', 'DApps']),
      t('Τι είναι το DeFi (Decentralized Finance)', 'DeFi decentralized finance', 'what-is', 40, ['lending', 'yield', 'DEX']),
      t('Τι είναι το Web3', 'Web3', 'what-is', 40, ['decentralized internet', 'blockchain', 'token economy']),
      t('Τι είναι τα Smart Contracts', 'smart contracts', 'what-is', 45, ['self-executing', 'Ethereum', 'Solidity']),
      t('Τι είναι το Cryptocurrency Wallet', 'crypto wallet', 'guide', 30, ['hot cold wallet', 'private key', 'Ledger MetaMask']),
      t('Τι είναι το Stablecoin', 'stablecoin', 'what-is', 35, ['USDC USDT', 'pegged', 'algorithmic stable']),
      t('Τι είναι το Digital Banking', 'digital banking', 'what-is', 25, ['neobank', 'Revolut', 'online banking']),
      t('Τι είναι τα Open Banking APIs', 'open banking API', 'what-is', 40, ['PSD2', 'bank APIs', 'third-party']),
      t('Τι είναι το Buy Now Pay Later (BNPL)', 'buy now pay later BNPL', 'what-is', 25, ['Klarna', 'Afterpay', 'consumer credit']),
      t('Τι είναι τα CBDCs (Ψηφιακά Νομίσματα Τράπεζας)', 'CBDC ψηφιακό νόμισμα', 'what-is', 40, ['digital euro', 'central bank', 'monetary policy']),
      t('Τι είναι το Crypto Mining', 'cryptocurrency mining', 'what-is', 35, ['proof of work', 'GPU mining', 'energy consumption']),
      t('Proof of Work vs Proof of Stake: Διαφορές', 'proof of work vs stake', 'comparison', 45, ['consensus mechanism', 'energy', 'Ethereum merge']),
      t('Ασφάλεια Κρυπτονομισμάτων: Πώς να Προστατέψεις Assets', 'ασφάλεια crypto', 'guide', 35, ['hardware wallet', '2FA', 'seed phrase']),
      t('Τι είναι το DAO', 'DAO decentralized autonomous organization', 'what-is', 45, ['governance token', 'voting', 'decentralized']),
      t('Τι είναι το Robo-Advisor', 'robo advisor', 'what-is', 30, ['automated investing', 'portfolio', 'Betterment']),
      t('Τι είναι το Peer-to-Peer Lending', 'P2P lending', 'what-is', 35, ['crowdlending', 'fintech loan', 'marketplace lending']),
      t('Τι είναι τα Digital Payments', 'digital payments', 'what-is', 20, ['contactless', 'Apple Pay', 'QR payments']),
      t('Ρύθμιση Κρυπτονομισμάτων στην Ευρώπη', 'ρύθμιση crypto Ευρώπη', 'analysis', 40, ['MiCA', 'EU crypto', 'compliance']),
      t('Τι είναι το Yield Farming και Liquidity Mining', 'yield farming DeFi', 'what-is', 55, ['APY', 'liquidity pool', 'DeFi protocols']),
      t('Μέλλον του Fintech', 'μέλλον fintech', 'analysis', 35, ['embedded finance', 'super apps', 'AI banking']),
    ],
  },

  // ── 15. Leadership & Management ──────────────────────────────────────────────
  {
    name: 'Leadership',
    slug: 'leadership',
    pillarKeyword: 'ηγεσία',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Αναπτύξτε τις δεξιότητες ηγεσίας που χρειάζεται η σύγχρονη οργάνωση. Transformational leadership, emotional intelligence, performance management, conflict resolution και team building — οδηγοί για managers, team leaders και executives που θέλουν να εμπνέουν και να αποδίδουν.',
    topics: [
      t('Τι είναι η Ηγεσία', 'ηγεσία', 'what-is', 20, ['leadership', 'vision', 'inspiration']),
      t('Στυλ Ηγεσίας: Ποιο Ταιριάζει σε Εσένα', 'στυλ ηγεσίας', 'explainer', 25, ['autocratic democratic', 'laissez-faire', 'situational']),
      t('Τι είναι η Transformational Leadership', 'transformational leadership', 'explainer', 35, ['inspire change', 'motivation', 'vision']),
      t('Τι είναι η Servant Leadership', 'servant leadership', 'explainer', 35, ['employee-first', 'support', 'empowerment']),
      t('Emotional Intelligence στην Ηγεσία', 'emotional intelligence ηγεσία', 'analysis', 30, ['EQ leaders', 'empathy', 'self-regulation']),
      t('Πώς να Κινητοποιείς Ομάδα', 'κινητοποίηση ομάδας', 'guide', 25, ['intrinsic motivation', 'recognition', 'purpose']),
      t('Τι είναι το Delegation', 'delegation ανάθεση εργασιών', 'guide', 25, ['task assignment', 'empowerment', 'trust']),
      t('Πώς να Δίνεις Constructive Feedback', 'feedback culture', 'guide', 30, ['SBI model', 'radical candor', 'performance']),
      t('Τι είναι το Performance Management', 'performance management', 'guide', 35, ['appraisals', 'goals', 'continuous feedback']),
      t('Πώς να Κάνεις 1-on-1 Meetings Αποτελεσματικά', '1 on 1 meetings', 'guide', 25, ['agenda', 'employee development', 'trust']),
      t('Τι είναι το Micromanagement και Πώς να το Αποφύγεις', 'micromanagement', 'analysis', 25, ['autonomy', 'trust', 'control']),
      t('Remote Team Management: Οδηγός', 'remote team management', 'guide', 30, ['async', 'tools', 'culture']),
      t('Τι είναι το Conflict Resolution', 'conflict resolution', 'guide', 30, ['mediation', 'communication', 'win-win']),
      t('Τι είναι το Change Management', 'change management', 'guide', 40, ['Kotter 8 steps', 'resistance', 'transformation']),
      t('Πώς να Χτίσεις High-Performance Team', 'high performance team', 'guide', 35, ['trust', 'accountability', 'results']),
      t('Τι είναι το Psychological Safety', 'psychological safety', 'what-is', 35, ['Google Project Aristotle', 'trust', 'innovation']),
      t('Diversity και Inclusion: Γιατί Μετράει', 'diversity inclusion leadership', 'guide', 30, ['DEI', 'inclusive teams', 'bias']),
      t('Τι είναι το Succession Planning', 'succession planning', 'what-is', 40, ['talent pipeline', 'leadership development', 'continuity']),
      t('Πώς να Εμπνέεις Innovation στην Ομάδα', 'innovation leadership', 'guide', 35, ['creative culture', 'psychological safety', 'experimentation']),
      t('Τι είναι το Talent Management', 'talent management', 'guide', 40, ['retention', 'development', 'succession']),
      t('Agile Leadership: Ηγεσία στην Εποχή της Αβεβαιότητας', 'agile leadership', 'explainer', 40, ['adaptability', 'iterative', 'agile values']),
      t('Τι είναι το Strategic Thinking', 'strategic thinking', 'guide', 35, ['long-term vision', 'pattern recognition', 'decision making']),
      t('Executive Presence: Πώς να Επικοινωνείς ως Leader', 'executive presence', 'guide', 35, ['gravitas', 'communication', 'confidence']),
      t('Πώς να Κάνεις Αποφάσεις υπό Πίεση', 'αποφάσεις υπό πίεση', 'guide', 30, ['decision making', 'stress', 'frameworks']),
      t('Τι είναι το Agile OKR', 'agile OKR', 'guide', 40, ['OKR alignment', 'agile goals', 'quarterly planning']),
    ],
  },

  // ── 16. Automation & No-Code ─────────────────────────────────────────────────
  {
    name: 'Αυτοματοποίηση',
    slug: 'automation',
    pillarKeyword: 'αυτοματοποίηση',
    dbCategory: 'Τεχνολογία',
    description: 'Αυτοματοποιήστε επαναλαμβανόμενες εργασίες και χτίστε workflows χωρίς κώδικα. Zapier, Make, n8n, RPA, No-Code και Low-Code πλατφόρμες — πρακτικοί οδηγοί για επαγγελματίες και επιχειρήσεις που θέλουν να εξοικονομήσουν χρόνο και να αυξήσουν αποδοτικότητα.',
    topics: [
      t('Τι είναι η Αυτοματοποίηση Εργασιών', 'αυτοματοποίηση εργασιών', 'what-is', 25, ['workflow automation', 'productivity', 'efficiency']),
      t('Τι είναι το No-Code', 'no-code ανάπτυξη', 'what-is', 20, ['no-code tools', 'citizen developer', 'visual development']),
      t('Τι είναι το Low-Code', 'low-code platform', 'what-is', 25, ['low-code development', 'faster apps', 'visual coding']),
      t('No-Code vs Low-Code: Διαφορές', 'no-code vs low-code', 'comparison', 25, ['platform comparison', 'use cases', 'developer']),
      t('Τι είναι το Zapier: Πλήρης Οδηγός', 'Zapier οδηγός', 'guide', 20, ['integrations', 'triggers', 'automated workflows']),
      t('Τι είναι το Make (Integromat)', 'Make automation', 'guide', 25, ['visual automation', 'scenarios', 'integrations']),
      t('Zapier vs Make: Ποιο να Επιλέξεις', 'Zapier vs Make σύγκριση', 'comparison', 25, ['pricing', 'features', 'automation platforms']),
      t('Τι είναι το RPA (Robotic Process Automation)', 'RPA robotic process automation', 'what-is', 40, ['bots', 'UiPath', 'process automation']),
      t('Τι είναι το n8n: Open-Source Automation', 'n8n automation', 'guide', 35, ['self-hosted automation', 'open source', 'workflows']),
      t('Τι είναι το Webflow', 'Webflow website builder', 'what-is', 25, ['no-code websites', 'CMS', 'visual design']),
      t('Τι είναι το Bubble', 'Bubble no-code app', 'what-is', 30, ['web app builder', 'no-code SaaS', 'Bubble.io']),
      t('Τι είναι το Airtable: Database για Όλους', 'Airtable database', 'guide', 25, ['spreadsheet database', 'no-code', 'project management']),
      t('Πώς να Αυτοματοποιήσεις Email Marketing', 'email marketing automation', 'guide', 30, ['drip campaigns', 'triggers', 'Mailchimp sequences']),
      t('Πώς να Αυτοματοποιήσεις Social Media', 'social media automation', 'guide', 25, ['Buffer', 'scheduling', 'content distribution']),
      t('Τι είναι τα Chatbots και AI Assistants', 'chatbots AI', 'what-is', 30, ['customer service bot', 'Intercom', 'conversational AI']),
      t('AI Automation Tools: Τα Καλύτερα', 'AI automation tools', 'best-of', 20, ['Zapier AI', 'Make AI', 'workflow AI']),
      t('Πώς να Φτιάξεις No-Code App', 'no-code app development', 'tutorial', 30, ['Bubble Glide', 'MVP', 'mobile app']),
      t('Τι είναι το Business Process Automation (BPA)', 'business process automation BPA', 'guide', 40, ['process optimization', 'efficiency', 'digital transformation']),
      t('Τι είναι το Hyperautomation', 'hyperautomation', 'what-is', 50, ['AI RPA', 'intelligent automation', 'Gartner']),
      t('E-commerce Automation: Αυτοματοποίησε τη Δουλειά σου', 'e-commerce automation', 'guide', 35, ['order processing', 'inventory', 'customer service']),
      t('Marketing Automation: Πλήρης Οδηγός', 'marketing automation οδηγός', 'guide', 35, ['HubSpot automation', 'lead nurturing', 'triggers']),
      t('Τι είναι το IFTTT', 'IFTTT automation', 'what-is', 20, ['if this then that', 'simple automation', 'IoT']),
      t('CRM Automation: Αυτοματοποίηση Πωλήσεων', 'CRM automation', 'guide', 35, ['HubSpot Salesforce', 'pipeline', 'follow-up']),
      t('Τι είναι το Data Automation', 'data automation', 'what-is', 40, ['ETL', 'data pipelines', 'integration']),
      t('Μέλλον της Αυτοματοποίησης και AI Agents', 'μέλλον αυτοματοποίησης AI', 'analysis', 35, ['agentic AI', 'autonomous workflows', 'future work']),
    ],
  },

  // ── 17. UX/UI Design ────────────────────────────────────────────────────────
  {
    name: 'UX/UI Design',
    slug: 'ux-ui',
    pillarKeyword: 'UX design',
    dbCategory: 'Τεχνολογία',
    description: 'Σχεδιάστε ψηφιακές εμπειρίες που οι χρήστες αγαπούν. UX research, wireframing, prototyping, Figma, design systems, accessibility και conversion-centered design — ολοκληρωμένοι οδηγοί για designers, product managers και developers που θέλουν να δημιουργούν εξαιρετικά UI/UX.',
    topics: [
      t('Τι είναι το UX Design', 'UX design', 'what-is', 25, ['user experience', 'usability', 'research']),
      t('Τι είναι το UI Design', 'UI design', 'what-is', 20, ['user interface', 'visual design', 'interaction']),
      t('UX vs UI Design: Τι είναι Διαφορετικό', 'UX vs UI design', 'comparison', 20, ['user experience interface', 'design roles', 'process']),
      t('Τι είναι το Design Thinking', 'design thinking', 'what-is', 30, ['problem solving', 'empathy', 'IDEO']),
      t('Τι είναι τα User Personas', 'user personas', 'guide', 25, ['target user', 'research', 'empathy map']),
      t('Τι είναι το User Research', 'user research UX', 'guide', 35, ['interviews', 'surveys', 'usability testing']),
      t('Τι είναι το Wireframing', 'wireframing UX', 'what-is', 25, ['low-fidelity', 'layout', 'structure']),
      t('Τι είναι το Prototyping', 'prototyping UX', 'what-is', 25, ['interactive prototype', 'Figma', 'testing']),
      t('Τι είναι το Usability Testing', 'usability testing', 'guide', 35, ['user testing', 'tasks', 'think-aloud']),
      t('Τι είναι η Information Architecture', 'information architecture', 'what-is', 40, ['IA', 'navigation', 'content structure']),
      t('Τι είναι τα Design Systems', 'design systems', 'what-is', 35, ['component library', 'tokens', 'Figma system']),
      t('Τι είναι το Figma: Πλήρης Οδηγός', 'Figma design tool', 'guide', 25, ['UI design', 'collaboration', 'prototyping']),
      t('Web Accessibility: Σχεδιάζοντας για Όλους', 'web accessibility WCAG', 'guide', 30, ['WCAG', 'screen readers', 'inclusive design']),
      t('Τι είναι το Mobile-First Design', 'mobile first design', 'guide', 25, ['responsive', 'mobile UX', 'breakpoints']),
      t('Τι είναι η Color Theory στο Design', 'color theory design', 'explainer', 30, ['color psychology', 'palette', 'contrast']),
      t('Τι είναι η Typography στο Web', 'typography design web', 'explainer', 25, ['fonts', 'readability', 'type hierarchy']),
      t('Τι είναι τα UX Design Patterns', 'UX design patterns', 'explainer', 35, ['common patterns', 'conventions', 'best practices']),
      t('Conversion-Centered Design: UX για Πωλήσεις', 'conversion centered design', 'guide', 40, ['landing pages', 'CTA', 'persuasion']),
      t('Dark Mode Design: Best Practices', 'dark mode design', 'guide', 30, ['contrast', 'OLED', 'user preference']),
      t('Τι είναι το Atomic Design', 'atomic design', 'explainer', 40, ['atoms molecules organisms', 'Brad Frost', 'component']),
      t('A/B Testing στο UX Design', 'A/B testing UX', 'guide', 35, ['split testing UX', 'data-driven design', 'optimization']),
      t('Τι είναι το Eye-Tracking στο UX', 'eye tracking UX research', 'explainer', 40, ['heatmaps', 'F-pattern', 'visual attention']),
      t('AI στο UX Design: Ευκαιρίες και Εργαλεία', 'AI UX design', 'analysis', 35, ['Figma AI', 'Galileo', 'AI prototyping']),
      t('Τι είναι το Micro-interactions', 'micro-interactions design', 'explainer', 35, ['animation', 'feedback', 'delight']),
      t('Τάσεις UX/UI Design', 'UX UI design trends', 'analysis', 30, ['glassmorphism', 'neomorphism', 'design 2024']),
    ],
  },

  // ── 18. Remote Work ──────────────────────────────────────────────────────────
  {
    name: 'Remote Work',
    slug: 'remote-work',
    pillarKeyword: 'τηλεργασία',
    dbCategory: 'Επιχειρηματικότητα',
    description: 'Ο πλήρης οδηγός τηλεργασίας για εργαζόμενους και οργανισμούς. Home office setup, async communication, remote team management, digital nomad lifestyle και work-life balance — πρακτικές στρατηγικές για να δουλεύετε αποδοτικά από οπουδήποτε.',
    topics: [
      t('Τι είναι η Τηλεργασία', 'τηλεργασία', 'what-is', 15, ['remote work', 'work from home', 'WFH']),
      t('Πλεονεκτήματα Τηλεργασίας', 'πλεονεκτήματα τηλεργασίας', 'analysis', 15, ['flexibility', 'work life balance', 'productivity']),
      t('Μειονεκτήματα Τηλεργασίας', 'μειονεκτήματα τηλεργασίας', 'analysis', 15, ['isolation', 'communication', 'home distractions']),
      t('Τι είναι το Hybrid Work Model', 'hybrid work model', 'what-is', 20, ['office remote mix', 'flexible work', 'hybrid schedule']),
      t('Τα Καλύτερα Εργαλεία Τηλεργασίας', 'εργαλεία τηλεργασίας', 'best-of', 15, ['Zoom Slack', 'Notion Asana', 'collaboration tools']),
      t('Πώς να Διαχειριστείς Remote Team', 'remote team management', 'guide', 25, ['async', 'check-ins', 'trust']),
      t('Τι είναι το Asynchronous Work', 'asynchronous work', 'what-is', 25, ['async communication', 'non-real-time', 'flexibility']),
      t('Home Office Setup: Πώς να Στήσεις Τέλειο Γραφείο', 'home office setup', 'guide', 15, ['ergonomics', 'equipment', 'productivity space']),
      t('Πώς να Παραμείνεις Παραγωγικός Δουλεύοντας Σπίτι', 'παραγωγικότητα σπίτι', 'guide', 15, ['focus', 'routine', 'boundaries']),
      t('Digital Nomad Lifestyle: Πλεονεκτήματα και Προκλήσεις', 'digital nomad', 'guide', 20, ['travel work', 'coliving', 'nomad visa']),
      t('Remote Work Culture: Πώς να την Χτίσεις', 'remote work culture', 'guide', 25, ['team bonding', 'values', 'async first']),
      t('Τι είναι το Coworking Space', 'coworking space', 'what-is', 20, ['shared office', 'WeWork', 'community']),
      t('Remote Onboarding: Πώς να Υποδεχτείς Νέους Υπαλλήλους', 'remote onboarding', 'guide', 30, ['new hire', 'virtual onboarding', 'culture fit']),
      t('Virtual Team Building Activities', 'virtual team building', 'guide', 25, ['online games', 'virtual coffee', 'engagement']),
      t('Remote Work Security: Πώς να Προστατεύεσαι', 'remote work security', 'guide', 25, ['VPN', 'endpoint security', 'data protection']),
      t('Work-from-Home Burnout: Αναγνώριση και Αντιμετώπιση', 'work from home burnout', 'guide', 20, ['isolation', 'overwork', 'recovery']),
      t('Τι είναι το 4-Day Work Week', '4 day work week', 'analysis', 25, ['reduced hours', 'Iceland experiment', 'productivity']),
      t('Gig Economy: Η Εργασία του Μέλλοντος', 'gig economy', 'what-is', 25, ['freelance economy', 'Uber economy', 'independent workers']),
      t('Τι είναι το Distributed Team', 'distributed teams', 'what-is', 25, ['global team', 'time zones', 'async first']),
      t('Πώς να Επικοινωνείς Αποτελεσματικά σε Remote Ομάδα', 'επικοινωνία remote team', 'guide', 25, ['written communication', 'video calls', 'documentation']),
      t('Remote Work για Εταιρείες: ROI και Αποτελέσματα', 'remote work ROI', 'analysis', 30, ['cost savings', 'productivity', 'talent pool']),
      t('Τι είναι το BYOD Policy', 'BYOD bring your own device', 'what-is', 30, ['device policy', 'security', 'MDM']),
      t('Νομικά Ζητήματα Τηλεργασίας', 'τηλεργασία νομικά', 'guide', 35, ['contracts', 'taxation', 'labor law']),
      t('Μελλοντικό της Εργασίας: Remote, Hybrid, AI', 'μέλλον εργασίας', 'analysis', 30, ['future of work', 'AI jobs', 'workplace 2030']),
      t('Πώς να Χτίσεις Remote Employer Brand', 'remote employer brand', 'guide', 30, ['attract talent', 'culture', 'remote-first']),
    ],
  },

  // ── 19. Ψηφιακός Μετασχηματισμός ────────────────────────────────────────────
  {
    name: 'Ψηφιακός Μετασχηματισμός',
    slug: 'digital-transformation',
    pillarKeyword: 'ψηφιακός μετασχηματισμός',
    dbCategory: 'Τεχνολογία',
    description: 'Οδηγός ψηφιακού μετασχηματισμού για επιχειρήσεις κάθε μεγέθους. IoT, Industry 4.0, predictive analytics, digital twin, API economy και process mining — στρατηγικές και τεχνολογίες για οργανισμούς που θέλουν να μετασχηματιστούν και να παραμείνουν ανταγωνιστικοί.',
    topics: [
      t('Τι είναι ο Ψηφιακός Μετασχηματισμός', 'ψηφιακός μετασχηματισμός', 'what-is', 30, ['digital transformation', 'DX', 'digitalization']),
      t('Πώς να Κάνεις Ψηφιακό Μετασχηματισμό', 'digital transformation strategy', 'guide', 40, ['change management', 'technology adoption', 'roadmap']),
      t('Τι είναι το Internet of Things (IoT)', 'IoT internet of things', 'what-is', 30, ['connected devices', 'sensors', 'smart home']),
      t('Τι είναι το Smart Home', 'smart home', 'what-is', 20, ['home automation', 'Alexa Google Home', 'IoT devices']),
      t('Τι είναι το Smart City', 'smart city', 'what-is', 30, ['urban technology', 'sensors', 'data city management']),
      t('Τι είναι η Industry 4.0', 'industry 4.0', 'what-is', 40, ['fourth industrial revolution', 'cyber physical', 'automation']),
      t('Τι είναι το Digital Twin', 'digital twin', 'what-is', 45, ['virtual replica', 'simulation', 'manufacturing']),
      t('Τι είναι το 5G για Επιχειρήσεις', '5G επιχειρήσεις', 'analysis', 35, ['5G business', 'IoT 5G', 'low latency']),
      t('Τι είναι το Predictive Analytics', 'predictive analytics', 'what-is', 45, ['forecasting', 'machine learning', 'business intelligence']),
      t('Τι είναι το Data Governance', 'data governance', 'what-is', 45, ['data management', 'compliance', 'data quality']),
      t('Τι είναι το API Economy', 'API economy', 'what-is', 40, ['API monetization', 'platform strategy', 'integration']),
      t('Τι είναι το Platform Business Model', 'platform business model', 'what-is', 40, ['marketplace', 'network effects', 'two-sided market']),
      t('Customer Experience Digitization', 'ψηφιακή εμπειρία πελάτη', 'guide', 35, ['CX', 'omnichannel', 'personalization']),
      t('Τι είναι η Ψηφιακή Ωριμότητα', 'digital maturity', 'guide', 40, ['digital capability', 'assessment', 'roadmap']),
      t('AR και VR στις Επιχειρήσεις', 'AR VR επιχειρήσεις', 'guide', 35, ['training', 'product visualization', 'virtual showrooms']),
      t('Τι είναι το Metaverse για Επιχειρήσεις', 'metaverse επιχειρήσεις', 'analysis', 35, ['virtual world', 'Meta', 'digital presence']),
      t('Τι είναι το Process Mining', 'process mining', 'what-is', 50, ['process analysis', 'Celonis', 'workflow optimization']),
      t('Τι είναι το Open Innovation', 'open innovation', 'what-is', 40, ['crowdsourcing', 'external R&D', 'collaboration']),
      t('Τι είναι το Digital Workplace', 'digital workplace', 'what-is', 30, ['remote collaboration', 'tools', 'employee experience']),
      t('RPA στη Βιομηχανία: Πρακτικές Εφαρμογές', 'RPA βιομηχανία', 'guide', 45, ['manufacturing automation', 'UiPath', 'process bots']),
      t('Τι είναι η Supply Chain Digitization', 'ψηφιακή αλυσίδα εφοδιασμού', 'what-is', 45, ['supply chain tech', 'visibility', 'blockchain supply']),
      t('Τεχνολογία και Βιωσιμότητα: Green Tech', 'green technology sustainability', 'analysis', 35, ['sustainable tech', 'carbon footprint', 'renewable energy tech']),
      t('Τι είναι το Edge AI', 'edge AI', 'what-is', 50, ['on-device AI', 'IoT AI', 'low latency inference']),
      t('Τι είναι το No-Code Digital Transformation', 'no-code digital transformation', 'guide', 30, ['citizen development', 'agility', 'innovation']),
      t('Μέλλον της Ψηφιακής Επιχείρησης', 'μέλλον ψηφιακή επιχείρηση', 'analysis', 35, ['AI first', 'autonomous operations', 'digital 2030']),
    ],
  },

  // ── 20. Future Technology ────────────────────────────────────────────────────
  {
    name: 'Future Technology',
    slug: 'future-tech',
    pillarKeyword: 'τεχνολογία μέλλον',
    dbCategory: 'AI',
    description: 'Εξερευνήστε τις τεχνολογίες που θα διαμορφώσουν το αύριο. Quantum computing, AR/VR, autonomous vehicles, biotechnology, CRISPR, nanotechnology και space tech — αναλυτικές παρουσιάσεις των επαναστατικών τεχνολογιών που αλλάζουν τη ζωή μας στη δεκαετία 2030.',
    topics: [
      t('Τι είναι το Quantum Computing', 'quantum computing κβαντικός', 'what-is', 55, ['qubits', 'superposition', 'quantum advantage']),
      t('Τι είναι τα Wearable Devices', 'wearable technology', 'what-is', 25, ['smartwatch', 'health trackers', 'AR glasses']),
      t('Τι είναι τα Brain-Computer Interfaces (BCI)', 'brain computer interface BCI', 'what-is', 55, ['Neuralink', 'neural implants', 'neurotechnology']),
      t('Τι είναι η Augmented Reality (AR)', 'augmented reality AR', 'what-is', 30, ['overlayed reality', 'Apple Vision Pro', 'AR apps']),
      t('Τι είναι η Virtual Reality (VR)', 'virtual reality VR', 'what-is', 30, ['immersive', 'Meta Quest', 'VR headsets']),
      t('AR vs VR vs MR: Διαφορές', 'AR VR MR διαφορές', 'comparison', 30, ['extended reality', 'use cases', 'devices']),
      t('Τι είναι τα Autonomous Vehicles', 'autonomous vehicles', 'what-is', 40, ['self-driving cars', 'Tesla', 'Waymo']),
      t('Τι είναι η Biotechnology', 'biotechnology βιοτεχνολογία', 'what-is', 45, ['genetics', 'pharma tech', 'bioinformatics']),
      t('Τι είναι το 6G', '6G τεχνολογία', 'what-is', 50, ['beyond 5G', 'terahertz', '2030 connectivity']),
      t('Τι είναι η Smart Agriculture', 'precision agriculture', 'what-is', 40, ['IoT farming', 'drones', 'smart irrigation']),
      t('Τεχνολογία και Κλιματική Αλλαγή', 'τεχνολογία κλιματική αλλαγή', 'analysis', 35, ['cleantech', 'carbon capture', 'renewable energy']),
      t('Τι είναι το Sustainable Technology', 'sustainable technology', 'what-is', 35, ['green tech', 'circular economy', 'eco-design']),
      t('Τι είναι η Gene Editing (CRISPR)', 'CRISPR gene editing', 'what-is', 55, ['genetic engineering', 'DNA', 'bioethics']),
      t('Τι είναι το Synthetic Biology', 'synthetic biology', 'what-is', 60, ['engineered organisms', 'biofuels', 'bio-manufacturing']),
      t('Τι είναι η Nanotechnology', 'nanotechnology νανοτεχνολογία', 'what-is', 55, ['nanoscale', 'materials', 'medicine']),
      t('Τι είναι το SpaceTech', 'space technology', 'what-is', 40, ['rockets', 'SpaceX', 'satellite internet']),
      t('Τι είναι το Energy Storage Technology', 'energy storage technology', 'what-is', 45, ['batteries', 'solid-state', 'grid storage']),
      t('Τι είναι το Ambient Computing', 'ambient computing', 'what-is', 50, ['ubiquitous computing', 'invisible tech', 'smart environment']),
      t('Μέλλον της Ψηφιακής Υγείας (Digital Health)', 'digital health future', 'analysis', 40, ['telemedicine', 'AI diagnosis', 'health wearables']),
      t('Τι είναι το Human Augmentation', 'human augmentation', 'what-is', 50, ['exoskeletons', 'cognitive enhancement', 'biohacking']),
      t('Τεχνολογία και Κοινωνία: Επιπτώσεις', 'technology society impact', 'analysis', 35, ['social media impact', 'tech ethics', 'digital divide']),
      t('Τι είναι η Technological Singularity', 'technological singularity', 'what-is', 60, ['superintelligence', 'exponential growth', 'Kurzweil']),
      t('Τι είναι η Post-Scarcity Economy', 'post scarcity economy', 'analysis', 55, ['automation abundance', 'UBI', 'future economics']),
      t('Τι είναι το Hyperloop', 'hyperloop technology', 'what-is', 35, ['high speed transport', 'Virgin Hyperloop', 'vacuum tube']),
      t('Μέλλον της Τεχνολογίας: Τι Έρχεται στη Δεκαετία 2030', 'μέλλον τεχνολογίας 2030', 'analysis', 40, ['AI 2030', 'quantum', 'biotech trends']),
    ],
  },
];

export function getAllTopics(): Array<EvergreenTopic & { cluster: string; clusterSlug: string }> {
  return CLUSTERS.flatMap((c) =>
    c.topics.map((topic) => ({ ...topic, cluster: c.name, clusterSlug: c.slug })),
  );
}

export function getClusterBySlug(slug: string): EvergreenCluster | undefined {
  return CLUSTERS.find((c) => c.slug === slug);
}

export function getClusterForKeyword(keyword: string): EvergreenCluster | undefined {
  const kw = keyword.toLowerCase();
  return CLUSTERS.find((c) =>
    c.topics.some((t) => t.primaryKeyword.toLowerCase() === kw),
  );
}
